platform: linux
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: 1.0.4
    username: ((docker-hub-username))
    password: ((docker-hub-password))
params:
  DEPLOYER_ROLE_ARN: ((deployer-role-arn-non-prod))
  DEPLOY_ENVIRONMENT: build
  DNS_DEPLOYER_ROLE_ARN: ((deployer-role-arn-production))
  DNS_STATE_BUCKET: ((dns-state-bucket))
  DNS_STATE_KEY: ((dns-state-key))
  NOTIFY_API_KEY: ((build-notify-api-key))
  STATE_BUCKET: digital-identity-dev-tfstate
  STATE_LOCKING_TABLE: digital-identity-dev-tfstate-locking
  TXMA_ACCOUNT_ID: ((build-txma-account-id))
  TEST_CLIENT_VERIFY_EMAIL_OTP: ((test-client-verify-email-otp))
  TEST_CLIENT_VERIFY_PHONE_NUMBER_OTP: ((test-client-verify-phone-number-otp))
  TEST_CLIENTS_ENABLED: false
inputs:
  - name: api-terraform-src
  - name: api-release
outputs:
  - name: terraform-outputs
run:
  path: /bin/sh
  args:
    - -euc
    - |
      if [[ "${DEPLOY_ENVIRONMENT}" == "build" ]]; then
        ENABLE_STATE_LOCKING=true
      else
        ENABLE_STATE_LOCKING=false
      fi

      cd "api-terraform-src/ci/terraform/account-management"
      terraform init -input=false \
        -backend-config "role_arn=${DEPLOYER_ROLE_ARN}" \
        -backend-config "bucket=${STATE_BUCKET}" \
        -backend-config "key=${DEPLOY_ENVIRONMENT}-account-managment-api-terraform.tfstate" \
        -backend-config "encrypt=true" \
        -backend-config "region=eu-west-2" \
        -backend-config "dynamodb_table=${STATE_LOCKING_TABLE}"

      terraform apply -auto-approve \
        -var "deployer_role_arn=${DEPLOYER_ROLE_ARN}" \
        -var "environment=${DEPLOY_ENVIRONMENT}" \
        -var "notify_api_key=${NOTIFY_API_KEY}" \
        -var 'logging_endpoint_arn=arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prod' \
        -var 'logging_endpoint_arns=["arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prod"]' \
        -var "lambda_zip_file=$(ls -1 ../../../../api-release/*.zip)" \
        -var "common_state_bucket=${STATE_BUCKET}" \
        -var "dns_state_bucket=${DNS_STATE_BUCKET}" \
        -var "dns_state_key=${DNS_STATE_KEY}" \
        -var "dns_state_role=${DNS_DEPLOYER_ROLE_ARN}" \
        -var "txma_account_id=${TXMA_ACCOUNT_ID}" \
        -var "test_client_verify_email_otp=${TEST_CLIENT_VERIFY_EMAIL_OTP}" \
        -var "test_client_verify_phone_number_otp=${TEST_CLIENT_VERIFY_PHONE_NUMBER_OTP}" \
        -var "test_clients_enabled=${TEST_CLIENTS_ENABLED}" \
        -var-file "${DEPLOY_ENVIRONMENT}-overrides.tfvars" \
        -var-file ${DEPLOY_ENVIRONMENT}-sizing.tfvars \
        -lock "${ENABLE_STATE_LOCKING}"

      terraform output --json > ../../../../terraform-outputs/${DEPLOY_ENVIRONMENT}-account-managment-api-terraform-outputs.json
