platform: linux
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: 1.0.4
    username: ((docker-hub-username))
    password: ((docker-hub-password))
params:
  DEPLOYER_ROLE_ARN: ((deployer-role-arn-non-prod))
  DEPLOY_ENVIRONMENT: build
  NOTIFY_API_KEY: ((build-notify-api-key))
  PASSWORD_PEPPER: ((build-password-pepper))
  STATE_BUCKET: digital-identity-dev-tfstate
  STATE_LOCKING_TABLE: digital-identity-dev-tfstate-locking
  TEST_CLIENT_EMAIL_ALLOWLIST: ((test-client-email-allowlist))
  DI_TOOLS_SIGNING_PROFILE_VERSION_ARN: ((di-tools-signing-profile-version-arn))
  DI_TOOLS_ACCOUNT_NUMBER: ((di-tools-account-id-non-prod))
inputs:
  - name: api-terraform-src
outputs:
  - name: terraform-outputs
run:
  path: /bin/sh
  args:
    - -euc
    - |
      if [[ "${DEPLOY_ENVIRONMENT}" == "build" ]]; then
        ENABLE_STATE_LOCKING=true
      else
        ENABLE_STATE_LOCKING=false
      fi

      cd "api-terraform-src/ci/terraform/shared"
      terraform init -input=false \
        -backend-config "role_arn=${DEPLOYER_ROLE_ARN}" \
        -backend-config "bucket=${STATE_BUCKET}" \
        -backend-config "key=${DEPLOY_ENVIRONMENT}-shared-terraform.tfstate" \
        -backend-config "encrypt=true" \
        -backend-config "region=eu-west-2" \
        -backend-config "dynamodb_table=${STATE_LOCKING_TABLE}"

      terraform apply -auto-approve \
        -var "deployer_role_arn=${DEPLOYER_ROLE_ARN}" \
        -var "environment=${DEPLOY_ENVIRONMENT}" \
        -var "test_client_email_allowlist=${TEST_CLIENT_EMAIL_ALLOWLIST}" \
        -var "password_pepper=${PASSWORD_PEPPER}" \
        -var "common_state_bucket=${STATE_BUCKET}" \
        -var "di_tools_signing_profile_version_arn=${DI_TOOLS_SIGNING_PROFILE_VERSION_ARN}" \
        -var "tools_account_id=${DI_TOOLS_ACCOUNT_NUMBER}" \
        -var-file ${DEPLOY_ENVIRONMENT}-stub-clients.tfvars \
        -var-file ${DEPLOY_ENVIRONMENT}-sizing.tfvars \
        -lock="${ENABLE_STATE_LOCKING}"

      terraform output --json > ../../../../terraform-outputs/${DEPLOY_ENVIRONMENT}-shared-terraform-outputs.json
